-- MySQL Script generated by MySQL Workbench
-- Seg 05 Nov 2018 17:11:49 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone` (
  `cod_telefone` INT NOT NULL,
  `ddd_telefone` INT NOT NULL,
  `num_telefone` INT NOT NULL,
  PRIMARY KEY (`cod_telefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sexo` (
  `cod_sexo` INT NOT NULL,
  `desc_sexo` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_sexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`piloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`piloto` (
  `idPiloto` INT NOT NULL,
  `cpf_piloto` INT NOT NULL,
  `breve` INT NOT NULL,
  `nome_piloto` VARCHAR(45) NOT NULL,
  `email_piloto` VARCHAR(45) NOT NULL,
  `data_nascimento_piloto` VARCHAR(45) NOT NULL,
  `telefone_cod_telefone` INT NOT NULL,
  `sexo_cod_sexo` INT NOT NULL,
  PRIMARY KEY (`idPiloto`, `breve`, `cpf_piloto`, `telefone_cod_telefone`, `sexo_cod_sexo`),
  INDEX `fk_piloto_telefone1_idx` (`telefone_cod_telefone` ASC),
  INDEX `fk_piloto_sexo1_idx` (`sexo_cod_sexo` ASC),
  CONSTRAINT `fk_piloto_telefone1`
    FOREIGN KEY (`telefone_cod_telefone`)
    REFERENCES `mydb`.`telefone` (`cod_telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_piloto_sexo1`
    FOREIGN KEY (`sexo_cod_sexo`)
    REFERENCES `mydb`.`sexo` (`cod_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `idCurso` INT NOT NULL,
  `nome_curso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instituicao` (
  `idinstituicao` INT NOT NULL,
  `nome_instituicao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idinstituicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instrutor` (
  `idinstrutor` INT NOT NULL,
  `piloto_idPiloto` INT NOT NULL,
  `curso_idCurso` INT NOT NULL,
  `instituicao_idinstituicao` INT NOT NULL,
  `data_diploma` DATE NOT NULL,
  PRIMARY KEY (`idinstrutor`, `piloto_idPiloto`, `curso_idCurso`, `instituicao_idinstituicao`),
  INDEX `fk_instrutor_piloto1_idx` (`piloto_idPiloto` ASC),
  INDEX `fk_instrutor_curso1_idx` (`curso_idCurso` ASC),
  INDEX `fk_instrutor_instituicao1_idx` (`instituicao_idinstituicao` ASC),
  CONSTRAINT `fk_instrutor_piloto1`
    FOREIGN KEY (`piloto_idPiloto`)
    REFERENCES `mydb`.`piloto` (`idPiloto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instrutor_curso1`
    FOREIGN KEY (`curso_idCurso`)
    REFERENCES `mydb`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instrutor_instituicao1`
    FOREIGN KEY (`instituicao_idinstituicao`)
    REFERENCES `mydb`.`instituicao` (`idinstituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mae`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mae` (
  `cod_mae` INT NOT NULL,
  `nome_mae` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_mae`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pai` (
  `cod_pai` INT NOT NULL,
  `nome_pai` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_pai`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filiacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`filiacao` (
  `cod_filiacao` INT NOT NULL,
  `mae_cod_mae` INT NOT NULL,
  `pai_cod_pai` INT NOT NULL,
  PRIMARY KEY (`cod_filiacao`, `mae_cod_mae`, `pai_cod_pai`),
  INDEX `fk_filiacao_mae1_idx` (`mae_cod_mae` ASC),
  INDEX `fk_filiacao_pai1_idx` (`pai_cod_pai` ASC),
  CONSTRAINT `fk_filiacao_mae1`
    FOREIGN KEY (`mae_cod_mae`)
    REFERENCES `mydb`.`mae` (`cod_mae`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filiacao_pai1`
    FOREIGN KEY (`pai_cod_pai`)
    REFERENCES `mydb`.`pai` (`cod_pai`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_civil` (
  `cod_estado_civil` INT NOT NULL,
  `desc_estado_civil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_estado_civil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pais` (
  `cod_pais` INT NOT NULL,
  `nome_pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `cod_estado` INT NOT NULL,
  `nome_estado` VARCHAR(45) NOT NULL,
  `pais_cod_pais` INT NOT NULL,
  PRIMARY KEY (`cod_estado`, `pais_cod_pais`),
  INDEX `fk_estado_pais_idx` (`pais_cod_pais` ASC),
  CONSTRAINT `fk_estado_pais`
    FOREIGN KEY (`pais_cod_pais`)
    REFERENCES `mydb`.`pais` (`cod_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidade` (
  `cod_cidade` INT NOT NULL,
  `nome_cidade` VARCHAR(45) NOT NULL,
  `estado_cod_estado` INT NOT NULL,
  PRIMARY KEY (`cod_cidade`, `estado_cod_estado`),
  INDEX `fk_cidade_estado1_idx` (`estado_cod_estado` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_cod_estado`)
    REFERENCES `mydb`.`estado` (`cod_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bairro` (
  `cod_bairro` INT NOT NULL,
  `nome_bairro` VARCHAR(45) NOT NULL,
  `cidade_cod_cidade` INT NOT NULL,
  PRIMARY KEY (`cod_bairro`, `cidade_cod_cidade`),
  INDEX `fk_bairro_cidade1_idx` (`cidade_cod_cidade` ASC),
  CONSTRAINT `fk_bairro_cidade1`
    FOREIGN KEY (`cidade_cod_cidade`)
    REFERENCES `mydb`.`cidade` (`cod_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`quadra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`quadra` (
  `cod_quadra` INT NOT NULL,
  `nome_quadra` VARCHAR(45) NOT NULL,
  `bairro_cod_bairro` INT NOT NULL,
  PRIMARY KEY (`cod_quadra`, `bairro_cod_bairro`),
  INDEX `fk_quadra_bairro1_idx` (`bairro_cod_bairro` ASC),
  CONSTRAINT `fk_quadra_bairro1`
    FOREIGN KEY (`bairro_cod_bairro`)
    REFERENCES `mydb`.`bairro` (`cod_bairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cep` (
  `cod_cep` INT NOT NULL,
  `quadra_cod_quadra` INT NOT NULL,
  PRIMARY KEY (`cod_cep`, `quadra_cod_quadra`),
  INDEX `fk_cep_quadra1_idx` (`quadra_cod_quadra` ASC),
  CONSTRAINT `fk_cep_quadra1`
    FOREIGN KEY (`quadra_cod_quadra`)
    REFERENCES `mydb`.`quadra` (`cod_quadra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`complemento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`complemento` (
  `cod_complemento` INT NOT NULL,
  `desc_complemento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_complemento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `cod_endereco` INT NOT NULL,
  `num_endereco` INT NOT NULL,
  `cep_cod_cep` INT NOT NULL,
  `complemento_cod_complemento` INT NOT NULL,
  PRIMARY KEY (`cod_endereco`, `cep_cod_cep`, `complemento_cod_complemento`),
  INDEX `fk_endereco_cep1_idx` (`cep_cod_cep` ASC),
  INDEX `fk_endereco_complemento1_idx` (`complemento_cod_complemento` ASC),
  CONSTRAINT `fk_endereco_cep1`
    FOREIGN KEY (`cep_cod_cep`)
    REFERENCES `mydb`.`cep` (`cod_cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_complemento1`
    FOREIGN KEY (`complemento_cod_complemento`)
    REFERENCES `mydb`.`complemento` (`cod_complemento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`escolaridade` (
  `cod_escolaridade` INT NOT NULL,
  `desc_escolaridade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_escolaridade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargo` (
  `cod_cargo` INT NOT NULL,
  `desc_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `mat_aluno` INT NOT NULL,
  `cpf_aluno` INT NOT NULL,
  `rg_aluno` VARCHAR(45) NOT NULL,
  `nome_aluno` VARCHAR(45) NOT NULL,
  `data_nascimento_aluno` DATE NOT NULL,
  `email_aluno` VARCHAR(45) NOT NULL,
  `filiacao_cod_filiacao` INT NOT NULL,
  `sexo_cod_sexo` INT NOT NULL,
  `estado_civil_cod_estado_civil` INT NOT NULL,
  `pais_cod_pais` INT NOT NULL,
  `cidade_cod_cidade` INT NOT NULL,
  `endereco_cod_endereco` INT NOT NULL,
  `telefone_cod_telefone` INT NOT NULL,
  `escolaridade_cod_escolaridade` INT NOT NULL,
  `cargo_cod_cargo` INT NOT NULL,
  PRIMARY KEY (`mat_aluno`, `cpf_aluno`, `rg_aluno`, `filiacao_cod_filiacao`, `sexo_cod_sexo`, `estado_civil_cod_estado_civil`, `pais_cod_pais`, `cidade_cod_cidade`, `endereco_cod_endereco`, `telefone_cod_telefone`, `escolaridade_cod_escolaridade`, `cargo_cod_cargo`),
  INDEX `fk_aluno_filiacao1_idx` (`filiacao_cod_filiacao` ASC),
  INDEX `fk_aluno_sexo1_idx` (`sexo_cod_sexo` ASC),
  INDEX `fk_aluno_estado_civil1_idx` (`estado_civil_cod_estado_civil` ASC),
  INDEX `fk_aluno_pais1_idx` (`pais_cod_pais` ASC),
  INDEX `fk_aluno_cidade1_idx` (`cidade_cod_cidade` ASC),
  INDEX `fk_aluno_endereco1_idx` (`endereco_cod_endereco` ASC),
  INDEX `fk_aluno_telefone1_idx` (`telefone_cod_telefone` ASC),
  INDEX `fk_aluno_escolaridade1_idx` (`escolaridade_cod_escolaridade` ASC),
  INDEX `fk_aluno_cargo1_idx` (`cargo_cod_cargo` ASC),
  CONSTRAINT `fk_aluno_filiacao1`
    FOREIGN KEY (`filiacao_cod_filiacao`)
    REFERENCES `mydb`.`filiacao` (`cod_filiacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_sexo1`
    FOREIGN KEY (`sexo_cod_sexo`)
    REFERENCES `mydb`.`sexo` (`cod_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_estado_civil1`
    FOREIGN KEY (`estado_civil_cod_estado_civil`)
    REFERENCES `mydb`.`estado_civil` (`cod_estado_civil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_pais1`
    FOREIGN KEY (`pais_cod_pais`)
    REFERENCES `mydb`.`pais` (`cod_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_cidade1`
    FOREIGN KEY (`cidade_cod_cidade`)
    REFERENCES `mydb`.`cidade` (`cod_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_endereco1`
    FOREIGN KEY (`endereco_cod_endereco`)
    REFERENCES `mydb`.`endereco` (`cod_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_telefone1`
    FOREIGN KEY (`telefone_cod_telefone`)
    REFERENCES `mydb`.`telefone` (`cod_telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_escolaridade1`
    FOREIGN KEY (`escolaridade_cod_escolaridade`)
    REFERENCES `mydb`.`escolaridade` (`cod_escolaridade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_cargo1`
    FOREIGN KEY (`cargo_cod_cargo`)
    REFERENCES `mydb`.`cargo` (`cod_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`saida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`saida` (
  `idsaida` INT NOT NULL,
  `hora_saida` DATETIME NULL,
  `hora_chegada` DATETIME NULL,
  `parecer` VARCHAR(256) NULL,
  `instrutor_idinstrutor` INT NOT NULL,
  `aluno_mat_aluno` INT NOT NULL,
  PRIMARY KEY (`idsaida`, `instrutor_idinstrutor`, `aluno_mat_aluno`),
  INDEX `fk_saida_instrutor1_idx` (`instrutor_idinstrutor` ASC),
  INDEX `fk_saida_aluno1_idx` (`aluno_mat_aluno` ASC),
  CONSTRAINT `fk_saida_instrutor1`
    FOREIGN KEY (`instrutor_idinstrutor`)
    REFERENCES `mydb`.`instrutor` (`idinstrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saida_aluno1`
    FOREIGN KEY (`aluno_mat_aluno`)
    REFERENCES `mydb`.`aluno` (`mat_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
